In [2]:
import cv2 as cv
import matplotlib.pyplot as plt
import numpy as np

In [28]:
img = cv.imread('qr_code.jpg')
qr = cv.QRCodeDetector()

_, code = qr.detect(img)
_, QR_string = qr.decode(img, code)
x, y, string = qr.detectAndDecode(img)

print(string)
print('')
print(x)
print(y)

[[  0   0   0 ...   0   0   0]
 [  0 255 255 ... 255 255   0]
 [  0 255   0 ...   0 255   0]
 ...
 [  0 255   0 ... 255 255   0]
 [  0 255 255 ... 255   0   0]
 [  0   0   0 ...   0 255   0]]

         (__) 
         (oo) 
   /------\/ 
  / |    ||   
 *  /\---/\ 
    ~~   ~~   


[[[471.64368 204.     ]
  [717.89343 204.     ]
  [708.30176 438.0374 ]
  [458.42676 433.97443]]]
